title: Robin Lovelace
tagline: 'Time to understand the world'
description: 'Geographer, environmental scientist, cyclist'
description: > # this means to ignore newlines until "baseurl:"
  environmental geographer, transport modeller, energy researcher
url: http://robinlovelace.net
name: Robin Lovelace
email: rob00x@gmail.com

url: "http://robinlovelace.net" 
twitter_username: robinlovelace
github_username:  robinlovelace
permalink: /:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
