title: Robin Lovelace
tagline: 'Time to understand the world'
description: 'Geographer, environmental scientist, cyclist'
url: http://robinlovelace.net
name: Robin Lovelace
email: rob00x@gmail.com


ipygments: true
comments: true
markdown: kramdown
paginate: 5

scholar:
  bibliography_template: "%{reference}"

gems:
  - jekyll-redirect-from


